[WIP] ES2023 support
SAP/ui5-builder pull request #1032
Opened 2024-06-18 12:05 UTC by flovogt

2024-06-19 15:24 UTC, RandomByte requested changes

2024-06-19 15:24 UTC, RandomByte commented on lib/lbt/bundle/Builder.js
> +	return str.replace(/^#!(.*)/g, "");
```suggestion
	return str.replace(/^#!(.*)/, "");
```

Global flag should not be necessary

2024-06-21 08:38 UTC, flovogt commented on lib/lbt/bundle/Builder.js
> +	return str.replace(/^#!(.*)/g, "");
done

2024-06-24 11:41 UTC, RandomByte approved these changes

2024-06-24 12:00 UTC, merged