[FIX] manifestEnhancer: Only use valid files for supportedLocales
SAP/ui5-builder pull request #1080
Opened 2024-09-05 07:37 UTC by matz3

This fixes two problems that could have occurred:

A properties file with an invalid locale was still taken into the list of supported locales, which then caused a runtime exception in the ResourceBundle as it validates the input.

Another problem was that properties files could have a valid name according to BCP47, but the file won't be ever requested with that name. This is due to the fact that the ResourceBundle does not use the variants / private use sections of the locale when creating the request URL.

In both cases, the properties file is now ignored and no entry for the supportedLocales is created.

2024-09-05 07:38 UTC, matz3 commented on lib/processors/manifestEnhancer.js
> +					log.verbose(`Skipping invalid locale '${locale}' for bundle '${i18nBundleUrl}'`);
Still open: What should happen in this case? Maybe rather an warning or even error log?

2024-09-11 08:13 UTC, matz3 commented on lib/processors/manifestEnhancer.js
> +					log.verbose(`Skipping invalid locale '${locale}' for bundle '${i18nBundleUrl}'`);
Decision: Log a warning and explain in commit message that the warning can be suppressed by manually maintaining the "supportedLocales".

2024-09-11 15:22 UTC, matz3 commented on lib/processors/manifestEnhancer.js
> +					log.verbose(`Skipping invalid locale '${locale}' for bundle '${i18nBundleUrl}'`);
Warning added via https://github.com/SAP/ui5-builder/pull/1080/commits/11ab19f778cfe4a9cae6cd31efadc6b4e797ef6c

> To be checked: Built-in handling of private extensions at runtime (1Q, 2Q, 3Q).

This just turned out to be a confusion based on a wrong comment / commit message. It referred to `variants`, but actually it was supposed to be `extensions`.

Extensions are not considered by the runtime code at all (i.e. can't appear in requests).
Private use is checked for the special SAP supportability locales, but the resulting request does not include an extension or private use section but will rather be e.g. `en_US_saptrc` (where `saptrc` is a variant).

2025-05-08 09:52 UTC, RandomByte requested changes

2025-05-08 09:52 UTC, RandomByte commented on lib/processors/manifestEnhancer.js
> +					log.warn(`Skipping invalid file '${fileName}' for bundle '${i18nBundleUrl}'`);
```suggestion
					log.warn(`Ignoring unexpected locale in filename '${fileName}' for bundle '${i18nBundleUrl}'`);
```

2025-05-09 13:02 UTC, codeworrior reviewed
I'm fine with the code change. I struggled a bit wit hthe commit message. Would you mind detailing what *"This is due to the fact that the ResourceBundle does use the legacy Java locale format for the request URL."* means?

I guess you refer to the fact that not very possible part of a BCP47 language tag will be used by ResourceBundle for the outgoing requests (e.g. the script is currently ignored except for sr_Latn).

The references in the runtime code are meanwhile outdated (code moved to LanguageFallback), but they use a commit ID, so they continue to work.

2025-05-16 10:14 UTC, codeworrior commented
I didn't doubt that the comment is in general right (it is). It just took me a while to get what exactly this means.

Adding some details or examples would have helped to understand the problem better. The difference between "_" and "-" is one such detail. The runtime also won't sent out certain subtags, e.g. the script (except for sr_Latn) and others (e.g. private extensions other than those for the pseudo languages).

Well, but I don't want to overcomplicate it.

2025-05-16 11:04 UTC, matz3 commented
@codeworrior thanks for your feedback. I've updated the commit message and also updated the code references.

2025-05-16 12:07 UTC, codeworrior approved these changes
Thank you for the updates! LGTM.

2025-05-16 12:18 UTC, merged