[INTERNAL] Add manifestCreator to processors facade
SAP/ui5-builder pull request #556
Opened 2020-11-30 16:24 UTC by codeworrior

2020-11-30 16:38 UTC, RandomByte approved these changes

2020-11-30 16:41 UTC, matz3 requested changes
manifestCreator has no JSDoc, so we should not make it available to be imported.
We should also add JSDoc and with that maybe re-check the public API.

2020-11-30 16:41 UTC, RandomByte submitted a review, later dismissed
Discarding my approval

2022-09-22 14:03 UTC, RandomByte commented
Done with https://github.com/SAP/ui5-builder/pull/648

2022-09-22 14:03 UTC, closed without merging