[FEATURE] Add 'libraryLessGenerator' processor
SAP/ui5-builder pull request #560
Opened 2020-12-09 13:33 UTC by matz3

2020-12-15 10:01 UTC, RandomByte requested changes

2020-12-15 11:43 UTC, RandomByte commented on lib/processors/libraryLessGenerator.js
> +		if (originalFilePath.endsWith("library.source.less")) {
Or rather [`path.basename(resolvedFilePath) === library.source.less`](https://nodejs.org/api/path.html#path_path_basename_path_ext)?

2020-12-15 19:23 UTC, RandomByte commented on test/lib/processors/libraryLessGenerator.js
> +test.serial("processor", async (t) => {
Is .serial actually necessary?

2020-12-15 19:27 UTC, RandomByte commented
I'm mostly fine with this change. But as discussed, we should rather merge it into a dedicated branch where we can then add the corresponding `generateThemeDesignerResources` task and merge everything into master once it's all done and tested 👍

2020-12-17 07:14 UTC, KlattG submitted a review, later dismissed
Just one small suggestion, otherwise LG

2020-12-17 07:14 UTC, KlattG commented on lib/processors/libraryLessGenerator.js
> + * <li>Imports to "base.less" files are adopted so that they point to the "BaseLib" that is available within
```suggestion
 * <li>Imports to "base.less" are adopted so that they point to the "BaseLib" that is available within
```

2020-12-17 09:13 UTC, matz3 commented on lib/processors/libraryLessGenerator.js
> + * <li>Imports to "base.less" files are adopted so that they point to the "BaseLib" that is available within
Thanks!

2020-12-17 09:56 UTC, RandomByte approved these changes

2020-12-17 09:58 UTC, merged

2020-12-17 10:02 UTC, matz3 commented
Merged into `generateThemeDesignerResources` branch. Will be merged into master as part of https://github.com/SAP/ui5-builder/pull/565.