Fix #486
SAP/ui5-builder pull request #576
Opened 2021-01-27 21:44 UTC by DerGuteWolf

manifestInfo.embeds can be initial and calling map on initial value will not work, thus default to empty array when initial

**Thank you for your contribution!** 🙌

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [ ] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-tooling/blob/master/CONTRIBUTING.md#-contributing-code)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-tooling/blob/master/CONTRIBUTING.md#how-to-contribute) section 
- [ ] [No merge commits](https://github.com/SAP/ui5-tooling/blob/master/docs/Guidelines.md#no-merge-commits)
- [ ] [Correct commit message style](https://github.com/SAP/ui5-tooling/blob/master/docs/Guidelines.md#commit-message-style)

2021-01-27 21:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/ui5-builder?pullRequest=576) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/ui5-builder?pullRequest=576) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/ui5-builder?pullRequest=576) it.</sub>

2021-01-28 08:39 UTC, tobiasso85 requested changes
Really good catch and a good fix, please also provide a test for this scenario
see similar test
https://github.com/SAP/ui5-builder/blob/master/test/lib/processors/versionInfoGenerator.js#L224

2021-01-28 09:59 UTC, DerGuteWolf commented
I added a similar test .

2021-01-28 10:40 UTC, tobiasso85 approved these changes
LGTM

2021-01-28 10:55 UTC, codeworrior commented
When merging, please adapt the summary line of the commit message according to our [guidelines](https://github.com/SAP/ui5-tooling/blob/master/docs/Guidelines.md#commit-message-style).

2021-01-28 11:26 UTC, DerGuteWolf commented
Suggestion for commit message:
---------------
[FIX] VersionInfoGenerator Processor: Correct Handling of non-existing manifestInfo.embeds

- manifestInfo.embeds can be initial when the sap.app section of a manifest does not contain an embeds property
- thus default to empty array for further processing eg with map
- 
Fixes: #486
---------------

2021-01-28 11:35 UTC, merged

2021-01-28 11:37 UTC, tobiasso85 commented
Fixes: https://github.com/SAP/ui5-tooling/issues/486