[INTERNAL] Introduce build task replaceBuildtime
SAP/ui5-builder pull request #645
Opened 2021-09-27 12:25 UTC by larskissel

Introduce the build task 'replaceBuildtime' used in
the LibraryBuilder. It replaces the placeholder
${buildtime} with a current timestamp in the
format "YYYYMMDD-HHmm".

JIRA: CPOUI5FOUNDATION-327

2021-09-27 12:59 UTC, RandomByte commented
Looking good! But I think this should be a [FEATURE] commit. Also, please mention in the commit message that the placeholder is only replaced in Global.js by default.

Also, an integration test would be good to make sure that the "Global.js"-pattern actually works in a real library. I think we can add another test in `test/lib/builder/builder.js`.

2021-09-27 13:00 UTC, RandomByte requested changes
See comment

2021-09-27 13:57 UTC, RandomByte commented
The integration test should also ensure that Global-dbg.js contains the replacement as well!

2021-09-28 17:47 UTC, RandomByte requested changes

2021-09-28 17:47 UTC, RandomByte commented on test/expected/build/sap.ui.core-buildtime/dest/resources/sap/ui/core/Core-dbg.js
> +console.log('${buildtime}');
According to our `.editorconfig`, there should always be a newline at the end of *.js files. Apparently your IDE doesn't seem to use this configuration. Please add newlines where missing, or my IDE will do it next time I save this file, creating unnecessary diffs 😉

2021-09-28 17:47 UTC, RandomByte commented on test/fixtures/sap.ui.core-buildtime/main/src/sap/ui/Global.js
> +// replacement of $\{buildtime\} is only made in sap/ui/Global.js
```suggestion
// replacement of $\{buildtime\} is only made in sap/ui/Global.js and Global-dbg.js
```

The comment really confused me in the expected `Global-dbg.js`

2021-09-29 14:13 UTC, RandomByte approved these changes

2021-10-04 08:17 UTC, RandomByte approved these changes

2021-10-04 08:22 UTC, matz3 approved these changes

2021-10-04 08:27 UTC, merged