[BREAKING] Removement of manifestBundler and generateManifestBundle
SAP/ui5-builder pull request #838
Opened 2022-11-09 13:16 UTC by flovogt

2022-11-10 14:20 UTC, matz3 requested changes
The task also should be removed from taskRepository and handled like the other removed tasks (e.g. "createDebugFiles")

2022-11-11 07:29 UTC, flovogt commented
> The task also should be removed from taskRepository and handled like the other removed tasks (e.g. "createDebugFiles")

Done

2022-11-11 07:47 UTC, matz3 submitted a review, later dismissed

2022-11-11 08:12 UTC, matz3 approved these changes

2022-11-11 09:00 UTC, merged