[INTERNAL] Bundler: Ignore non-JS resources when creating module name mapping
SAP/ui5-builder pull request #945
Opened 2023-10-10 15:27 UTC by RandomByte

This lead to issues where non-JS resources tagged as "IsDebugVariant"
(like source map resources) where processed since
ModuleName#getNonDebugName can only handle .js and .css extensions.

2023-10-10 19:02 UTC, flovogt approved these changes

2023-10-10 19:06 UTC, flovogt requested changes
As far as I see, you have started a smoke test run (id: 1518), so smoke tests fails. lets have a deeper look into it together.

2023-10-11 07:21 UTC, matz3 approved these changes

2023-10-11 07:56 UTC, RandomByte commented
Smoke tests will still fail after this PR is merged. However instead of failing due to an exception (which was caused by this not being able to resolve non-debug names for .map resources), it's only failing because of new warning logs now.

2023-10-11 07:56 UTC, merged